#!/usr/bin/env bash

set -euo pipefail

SCRIPTS_DIR="$(readlink -f "$(dirname "$0")")"
cd "${SCRIPTS_DIR}/.." || exit

. "${SCRIPTS_DIR}/bootstrap.sh"

driver_bind "vfio-pci" "${GPU_PCI_ID}" "${GPU_DEVICE_ID}"
driver_bind "vfio-pci" "${GPU_AUDIO_PCI_ID}" "${GPU_AUDIO_DEVICE_ID}"
