#!/usr/bin/env bash

set -euo pipefail

# Start up the VM with GPU passthrough
# Takes care of:
# * isolating GPU and enabling it back
# * isolating CPU cores from the host
# * (optionally) disconnecting the monitor, so it automatically picks up passthrough

# SCRIPT
# To be used by the script, don't modify
AUTORANDR_STATE=""

SCRIPTS_DIR="$(readlink -f "$(dirname "$0")")"
cd "${SCRIPTS_DIR}/.." || exit

. "${SCRIPTS_DIR}/bootstrap.sh"

# Set to true if you're running tests with a different XML
IGNORE_CONFIG_DIFF="${IGNORE_CONFIG_DIFF:-false}"

function sanity_checks() {
	if ! get_vm_config "${VM_NAME}" ""; then
		echoerr "Couldn't obtain config for vm ${VM_NAME}"
		echoerr "Did you remember to run scripts/setup first?"
		exit 1
	fi

	if ! check_vm_config_matches_template "${VM_NAME}" "${VM_CONFIG}"; then
		echoerr "VM config does not match the XML"
		echoerr "Either run scripts/setup or run with IGNORE_CONFIG_DIFF=true"
		if [[ "${IGNORE_CONFIG_DIFF}" == "true" ]]; then
			echo "Proceeding because of IGNORE_CONFIG_DIFF=true"
		else
			echo "Stopping..."
			exit 1
		fi
	fi
}

function pre_vm() {
	# Isolate GPU
	driver_bind "vfio-pci" "${GPU_PCI_ID}" "${GPU_DEVICE_ID}"
	driver_bind "vfio-pci" "${GPU_AUDIO_PCI_ID}" "${GPU_AUDIO_DEVICE_ID}"

	# Isolate CPU cores
	set_cpus_for_systemd "${HOST_CPUS}"

	# Start the network
	if ! sudo virsh net-info "${VM_NETWORK_NAME}" | grep Active | grep -q yes; then
		sudo virsh net-start "${VM_NETWORK_NAME}"
	fi
}

function post_vm() {
	echoerr "Cleaning up"

	# Is "Unisolate" even a word? :D
	# Unisolate GPU
	driver_bind "${GPU_DRIVER}" "${GPU_PCI_ID}" "${GPU_DEVICE_ID}"
	driver_bind "${GPU_AUDIO_DRIVER}" "${GPU_AUDIO_PCI_ID}" "${GPU_AUDIO_DEVICE_ID}"

	# Unisolate CPU cores
	set_cpus_for_systemd "${ALL_CPUS}"

	# Stop the network
	sudo virsh net-destroy "${VM_NETWORK_NAME}"

	# Enable the screen again
	if [[ "${AUTORANDR_ENABLE}" == "true" ]]; then
		autorandr -l "${AUTORANDR_DEFAULT}"
		if [[ "${AUTORANDR_STATE}" == "enabled" ]]; then
			echoerr "Reenabling autorandr service"
			sudo systemctl enable autorandr
		fi
	fi
}

function start_vm() {
	sudo virsh start "${VM_NAME}"
}

function wait_for_vm_to_shut_down() {
	# Switch the screen
	if [[ "${AUTORANDR_ENABLE}" == "true" ]]; then
		autorandr -l "${AUTORANDR_PASSTHROUGH}"
		AUTORANDR_STATE="$(systemctl is-enabled autorandr)"
		if [[ "${AUTORANDR_STATE}" == "enabled" ]]; then
			echoerr "Temporarily disabling autorandr service"
			sudo systemctl disable autorandr
		fi
	fi

	while true; do
		sudo virsh dominfo "${VM_NAME}" | grep State | grep -q "shut off" && return
		sleep 5
	done
}

check_sudo
sanity_checks

pre_vm

start_vm
wait_for_vm_to_shut_down

echo
post_vm
